# Generated by Django 5.0.7 on 2024-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='players',
            name='shirt_no',
            field=models.PositiveBigIntegerField(),
        ),
    ]
